print("B character's integer value is", ord('B'))
print("C character's integer value is", ord('C'))
print("D character's integer value is", ord('D'))
print("b character's integer value is", ord('b'))
print("c character's integer value is", ord('c'))
print("d character's integer value is", ord('d'))
print("0 character's integer value is", ord('0'))
print("1 character's integer value is", ord('1'))
print("2 character's integer value is", ord('2'))
print("$ character's integer value is", ord('*'))
print("+ character's integer value is", ord('+'))
print("Space character's integer value is", ord(' '))
